const list = [
  // React cơ bản & Todo App
  {
    id: 1,
    text: "JSX Basics",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Học cú pháp JSX và cách sử dụng JSX trong React.",
  },
  {
    id: 2,
    text: "Components",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu cách tạo và sử dụng React Components.",
  },
  {
    id: 3,
    text: "Props",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Học cách truyền dữ liệu giữa các component bằng Props.",
  },
  {
    id: 4,
    text: "Event Handling",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xử lý các sự kiện trong React.",
  },
  {
    id: 5,
    text: "useState",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Quản lý state bằng useState.",
  },
  {
    id: 6,
    text: "Controlled Input",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu controlled input trong React.",
  },
  {
    id: 7,
    text: "Array State",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Quản lý mảng dữ liệu trong state.",
  },
  {
    id: 8,
    text: "Todo Object",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng Todo dưới dạng object.",
  },
  {
    id: 9,
    text: "Add Todo",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Thêm Todo mới vào danh sách.",
  },
  {
    id: 10,
    text: "Delete Todo",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xóa Todo khỏi danh sách.",
  },
  {
    id: 11,
    text: "TodoItem Component",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tách Todo item thành component riêng.",
  },
  {
    id: 12,
    text: "Toggle Complete",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Thay đổi trạng thái hoàn thành của Todo.",
  },
  {
    id: 13,
    text: "Edit Todo",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Chỉnh sửa nội dung Todo.",
  },
  {
    id: 14,
    text: "TodoForm Component",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tạo component form để quản lý Todo.",
  },
  {
    id: 15,
    text: "TodoList Component",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tạo component hiển thị danh sách Todo.",
  },
  {
    id: 16,
    text: "Todo Statistics",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Hiển thị thống kê Todo.",
  },
  {
    id: 17,
    text: "Filter Todo",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Lọc Todo theo trạng thái.",
  },
  {
    id: 18,
    text: "localStorage",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Lưu dữ liệu Todo vào localStorage.",
  },

  // React Hooks & Core
  {
    id: 19,
    text: "Custom Hook",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tạo và sử dụng Custom Hook.",
  },
  {
    id: 20,
    text: "useEffect nâng cao",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu sâu hơn về useEffect.",
  },
  {
    id: 21,
    text: "useRef",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Sử dụng useRef để tham chiếu DOM và lưu giá trị.",
  },
  {
    id: 22,
    text: "useMemo",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tối ưu việc tính toán bằng useMemo.",
  },
  {
    id: 23,
    text: "useCallback",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tối ưu function bằng useCallback.",
  },
  {
    id: 24,
    text: "React.memo",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tối ưu việc render component bằng React.memo.",
  },
  {
    id: 25,
    text: "Context API",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Chia sẻ dữ liệu giữa các component bằng Context API.",
  },
  {
    id: 26,
    text: "Error Handling",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xử lý lỗi trong ứng dụng React.",
  },
  {
    id: 27,
    text: "Loading State",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Quản lý trạng thái loading.",
  },
  {
    id: 28,
    text: "React Router",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Quản lý routing và điều hướng trong React.",
  },
  {
    id: 29,
    text: "Fetch API",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Gọi API bằng Fetch API.",
  },
  {
    id: 30,
    text: "Axios",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Gọi API và xử lý request bằng Axios.",
  },

  // React nâng cao
  {
    id: 31,
    text: "CRUD với API",
    completed: true,
    priority: "medium",
    category: "study",
    important: true,
    description: "Thực hiện Create, Read, Update và Delete với API.",
  },
  {
    id: 32,
    text: "Form nâng cao",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng form với nhiều loại input và dữ liệu.",
  },
  {
    id: 33,
    text: "Form Validation",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Kiểm tra và xác thực dữ liệu trong form.",
  },
  {
    id: 34,
    text: "Search",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng chức năng tìm kiếm Todo.",
  },
  {
    id: 35,
    text: "Sort",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Sắp xếp danh sách Todo theo nhiều tiêu chí.",
  },
  {
    id: 36,
    text: "Pagination",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Chia danh sách dữ liệu thành nhiều trang.",
  },
  {
    id: 37,
    text: "Authentication",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng chức năng đăng nhập và xác thực người dùng.",
  },
  {
    id: 38,
    text: "Protected Routes",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Bảo vệ các route yêu cầu người dùng đăng nhập.",
  },
  {
    id: 39,
    text: "Redux Toolkit",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Quản lý global state bằng Redux Toolkit.",
  },
  {
    id: 40,
    text: "Zustand",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Quản lý state bằng Zustand.",
  },
  {
    id: 41,
    text: "TanStack Query / React Query",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Quản lý server state và API data.",
  },

  // CSS / UI / UX
  {
    id: 42,
    text: "CSS nâng cao",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Học các kỹ thuật CSS nâng cao.",
  },
  {
    id: 43,
    text: "Responsive Design",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Thiết kế giao diện phù hợp nhiều kích thước màn hình.",
  },
  {
    id: 44,
    text: "Tailwind CSS",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng giao diện bằng Tailwind CSS.",
  },
  {
    id: 45,
    text: "UI Component Library",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Sử dụng thư viện UI Component.",
  },
  {
    id: 46,
    text: "UX/UI cơ bản",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu các nguyên tắc cơ bản về UX/UI.",
  },

  // Development Tools
  {
    id: 47,
    text: "Git",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Quản lý source code bằng Git.",
  },
  {
    id: 48,
    text: "GitHub",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Lưu trữ và quản lý project trên GitHub.",
  },
  {
    id: 49,
    text: "ESLint",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Kiểm tra chất lượng và quy tắc code bằng ESLint.",
  },
  {
    id: 50,
    text: "Prettier",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Format code tự động bằng Prettier.",
  },
  {
    id: 51,
    text: "Clean Code",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Học cách viết code sạch và dễ bảo trì.",
  },
  {
    id: 52,
    text: "Project Structure",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tổ chức cấu trúc thư mục và source code.",
  },

  // Testing
  {
    id: 53,
    text: "Testing",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu testing trong ứng dụng web.",
  },
  {
    id: 54,
    text: "React Testing Library",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Kiểm thử React Component bằng React Testing Library.",
  },
  {
    id: 55,
    text: "Vitest",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Viết và chạy test bằng Vitest.",
  },

  // Next.js
  {
    id: 56,
    text: "Next.js cơ bản",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Làm quen với Next.js.",
  },
  {
    id: 57,
    text: "App Router",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu hệ thống App Router của Next.js.",
  },
  {
    id: 58,
    text: "Layout",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tạo Layout dùng chung trong Next.js.",
  },
  {
    id: 59,
    text: "Dynamic Routes",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng dynamic routes trong Next.js.",
  },
  {
    id: 60,
    text: "Server Components",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu Server Components.",
  },
  {
    id: 61,
    text: "Client Components",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu Client Components.",
  },
  {
    id: 62,
    text: "Data Fetching",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Lấy dữ liệu trong Next.js.",
  },
  {
    id: 63,
    text: "Server Actions",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Thực hiện server actions trong Next.js.",
  },
  {
    id: 64,
    text: "API Routes",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng API Routes.",
  },
  {
    id: 65,
    text: "Middleware",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Sử dụng Middleware trong Next.js.",
  },
  {
    id: 66,
    text: "Authentication với Next.js",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng authentication trong Next.js.",
  },
  {
    id: 67,
    text: "SEO",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tối ưu SEO cho ứng dụng Next.js.",
  },
  {
    id: 68,
    text: "Deployment",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Deploy ứng dụng Next.js.",
  },

  // Project React / Next.js
  {
    id: 69,
    text: "Hoàn thiện Todo App",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Hoàn thiện Todo App với các chức năng đã học.",
  },
  {
    id: 70,
    text: "Project sử dụng API",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng project React sử dụng API.",
  },
  {
    id: 71,
    text: "Project có Authentication",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng project có chức năng authentication.",
  },
  {
    id: 72,
    text: "Project React/Next.js hoàn chỉnh",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng một project React hoặc Next.js hoàn chỉnh.",
  },
  {
    id: 73,
    text: "GitHub Portfolio",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Chuẩn bị GitHub Portfolio cho việc ứng tuyển.",
  },
  {
    id: 74,
    text: "Deploy Project",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Đưa project lên môi trường production.",
  },
  {
    id: 75,
    text: "Portfolio / CV",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Chuẩn bị Portfolio và CV cho vị trí Frontend.",
  },

  // Backend - Node.js
  {
    id: 76,
    text: "Node.js cơ bản",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu nền tảng Node.js.",
  },
  {
    id: 77,
    text: "npm & package.json nâng cao",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu npm và package.json nâng cao.",
  },
  {
    id: 78,
    text: "Express.js",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng backend bằng Express.js.",
  },
  {
    id: 79,
    text: "REST API",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Thiết kế và xây dựng REST API.",
  },
  {
    id: 80,
    text: "Middleware Backend",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu middleware trong backend.",
  },
  {
    id: 81,
    text: "Error Handling Backend",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xử lý lỗi trong backend.",
  },
  {
    id: 82,
    text: "Environment Variables",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Quản lý biến môi trường.",
  },

  // Database
  {
    id: 83,
    text: "Database cơ bản",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu kiến thức cơ bản về database.",
  },
  {
    id: 84,
    text: "PostgreSQL",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Làm quen với PostgreSQL.",
  },
  {
    id: 85,
    text: "SQL cơ bản",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Học các câu lệnh SQL cơ bản.",
  },
  {
    id: 86,
    text: "Database CRUD",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Thực hiện CRUD với database.",
  },
  {
    id: 87,
    text: "Prisma ORM",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Làm việc với database bằng Prisma ORM.",
  },
  {
    id: 88,
    text: "Database Relationships",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu quan hệ giữa các bảng database.",
  },

  // Backend Authentication & Security
  {
    id: 89,
    text: "Backend Authentication",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng authentication ở backend.",
  },
  {
    id: 90,
    text: "JWT",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu JSON Web Token.",
  },
  {
    id: 91,
    text: "Authorization",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Phân quyền người dùng.",
  },
  {
    id: 92,
    text: "Password Hashing",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Bảo vệ mật khẩu bằng hashing.",
  },
  {
    id: 93,
    text: "API Security",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu các nguyên tắc bảo mật API.",
  },
  {
    id: 94,
    text: "CORS",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu và cấu hình CORS.",
  },
  {
    id: 95,
    text: "Rate Limiting",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Giới hạn số lượng request đến API.",
  },

  // Backend nâng cao
  {
    id: 96,
    text: "File Upload",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xử lý upload file ở backend.",
  },
  {
    id: 97,
    text: "API Pagination",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Phân trang dữ liệu từ API.",
  },
  {
    id: 98,
    text: "API Filtering & Search",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Lọc và tìm kiếm dữ liệu qua API.",
  },
  {
    id: 99,
    text: "API Validation",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Validate dữ liệu gửi đến API.",
  },
  {
    id: 100,
    text: "Backend Testing",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Kiểm thử backend và API.",
  },

  // Fullstack Integration
  {
    id: 101,
    text: "Kết nối React với Backend",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Kết nối frontend React với backend.",
  },
  {
    id: 102,
    text: "Kết nối Next.js với Backend",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Kết nối Next.js với backend.",
  },
  {
    id: 103,
    text: "Fullstack Authentication",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng authentication cho ứng dụng fullstack.",
  },
  {
    id: 104,
    text: "Fullstack CRUD",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng CRUD hoàn chỉnh từ frontend đến backend.",
  },
  {
    id: 105,
    text: "Frontend State + Server State",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Phân biệt và quản lý frontend state và server state.",
  },

  // Deployment
  {
    id: 106,
    text: "Docker cơ bản",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Tìm hiểu Docker cơ bản.",
  },
  {
    id: 107,
    text: "Deploy Frontend",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Deploy ứng dụng frontend.",
  },
  {
    id: 108,
    text: "Deploy Backend",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Deploy backend API.",
  },
  {
    id: 109,
    text: "Deploy Database",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Deploy database lên môi trường production.",
  },
  {
    id: 110,
    text: "Environment Production",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Cấu hình environment cho production.",
  },

  // Fullstack Projects
  {
    id: 111,
    text: "Fullstack Todo App",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng Todo App fullstack.",
  },
  {
    id: 112,
    text: "Fullstack Project với Authentication",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng project fullstack có authentication.",
  },
  {
    id: 113,
    text: "Fullstack Project có Database",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng project fullstack sử dụng database.",
  },
  {
    id: 114,
    text: "Fullstack Project hoàn chỉnh",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Xây dựng một project fullstack hoàn chỉnh.",
  },
  {
    id: 115,
    text: "Deploy Fullstack Project",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Deploy project fullstack lên production.",
  },
  {
    id: 116,
    text: "GitHub Fullstack Portfolio",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Chuẩn bị GitHub Portfolio cho các project fullstack.",
  },
  {
    id: 117,
    text: "Fullstack Portfolio / CV",
    completed: false,
    priority: "medium",
    category: "study",
    important: true,
    description: "Hoàn thiện Portfolio và CV theo hướng Fullstack.",
  },
];

export default list;
